{% set name = "s2geography" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/paleolimbot/s2geography/archive/refs/tags/{{ version }}.tar.gz
  sha256: 96e07816bd83a5e4cf8bcf7cf001705ed94026c9ba7cc586d4aa2559a54cc02d
  patches:
    # TODO: remove the patch below for the next s2geography release
    - 0001-cmake-exclude-nanoarrow-from-all-install-targets.patch

build:
  number: 1
  run_exports:
    # breaking changes are expected in minor 0.x releases
    - {{ pin_subpackage('s2geography', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.12,<4
    - make  # [unix]
  host:
    - openssl
    - libabseil
    - s2geometry

test:
  commands:
    - test -f ${PREFIX}/lib/libs2geography.dylib  # [osx]
    - test -f ${PREFIX}/lib/libs2geography.so     # [linux]
    - test -f ${PREFIX}/include/s2geography.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/s2geography/s2geographyConfig.cmake  # [unix]
    - if not exist %LIBRARY_BIN%\s2geography.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\s2geography.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\s2geography.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\s2geography\s2geographyConfig.cmake exit 1  # [win]


about:
  home: https://github.com/paleolimbot/s2geography
  license: Apache-2.0
  license_file: LICENSE.md
  summary: Simple features (ish) for s2geometry
  dev_url: https://github.com/paleolimbot/s2geography

extra:
  recipe-maintainers:
    - benbovy
    - jorisvandenbossche
