{% set name = "s2geography" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/paleolimbot/s2geography/archive/refs/tags/{{ version }}.tar.gz
  sha256: 877c6f9e3cfb78d0784bf08741e83620089f9351822b7672d4c13cd56712c8c1

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
    - cmake >=3.12,<4
    - make  # [linux]
  host:
    - openssl
    - libabseil
    - s2geometry
  run:
    - libabseil
    - s2geometry
test:
  commands:
    - test -f ${PREFIX}/lib/libs2geography.dylib  # [osx]
    - test -f ${PREFIX}/lib/libs2geography.so     # [linux]
    - test -f ${PREFIX}/include/s2geography.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/s2geography/s2geographyConfig.cmake  # [unix]
    - if not exist %LIBRARY_BIN%\s2geography.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\s2geography.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\s2geography.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\s2geography\s2geographyConfig.cmake exit 1  # [win]


about:
  home: https://github.com/paleolimbot/s2geography
  license: Apache-2.0
  license_file: LICENSE.md
  summary: Simple features (ish) for s2geometry
  dev_url: https://github.com/paleolimbot/s2geography

extra:
  recipe-maintainers:
    - benbovy
    - jorisvandenbossche
